name: nextluk_mobile
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Camera & Image Processing (FIXED: Removed duplicate image dependency)
  camera: ^0.10.5+5
  image_picker: ^1.0.4
  image: ^4.1.3  # Keep only this one, remove the ^4.0.17 version
  
  # State Management
  provider: ^6.1.1
  
  # UI & Styling
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  
  # Storage & Data
  shared_preferences: ^2.2.2
  
  # Network
  http: ^1.1.0
  
  # Utils
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/hairstyles/
    
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-Bold.ttf
          weight: 700
